version: '3.3'
services:
   ngnix:
      build: ./ngnix
      restart: unless-stopped
      ports:
         - '8080:80'
      volumes:
         - ./ngnix/ngnix-conf:/etc/ngnix/conf.d
   hlstream:
      build: .
      image: hlstream
      restart: unless-stopped
      command: ./full_code/full_pipeline
      port:
         - '80:8554'
      depends_on:
         - ngnix
      volumes:
         - streams_data:/app
volumes:
   streams_data:
