version: '3.3'
services:
   hlstream:
      build: .
      image: hlstream
      restart: unless-stopped
      ports:
         - '8554:8554'
      command: ./full_code/full_pipeline
      volumes:
         - streams_data:/app
      networks:
         - app-network
   nginx:
      image: nginx:latest
      restart: unless-stopped
      ports:
         - '8080:80'
      depends_on:
         - hlstream
      volumes:
         - ./nginx:/etc/nginx
         - streams_data:/usr/share/nginx/html
      networks:
         - app-network
volumes:
   streams_data:
networks:
   app-network:
      driver: bridge
