version: '3.3'
services:
   hlstream:
      build: .
      image: hlstream
      restart: unless-stopped
      ports:
         - '8554:8554'
      command: ./full_code/full_pipeline
      environment:
         NATS_URL: 'nats://216.48.181.154:5222'
         NATS_FRAME_STREAM: 'device_stream'
         NATS_FRAME_SUBJECT: 'stream.*.frame'
         RTSP_URL_1: 'rtsp://happymonk:admin123@192.168.1.2:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif'
         RTSP_URL_2: 'rtsp://192.168.1.102:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif'
         RTSP_URL_3: 'rtsp://192.168.1.103:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif'
         RTSP_URL_4: 'rtsp://192.168.1.104:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif'
         RTSP_URL_5: 'rtsp://192.168.1.105:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif'
         RTSP_URL_6: 'rtsp://192.168.1.106:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif'
      volumes:
         - streams_data:/app
      networks:
         - app-network
   nginx:
      image: nginx:latest
      restart: unless-stopped
      ports:
         - '8000:80'
         - '443:443'
      depends_on:
         - hlstream
      volumes:
         - ./nginx:/etc/nginx
         - streams_data:/usr/share/nginx/html
      networks:
         - app-network
volumes:
   streams_data:
networks:
   app-network:
      driver: bridge
