version: '3.7'
services:
  hlstest:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ./hls_stream
    ports:
      - "8060:8060"
        # volumes:
            # - .:/app