version: '3.3'
services:
   hlstream:
      build: .
      restart: unless-stopped
      command: ./full_code/full_pipeline
      ports:
         - '8554:8554'
      volumes:
         - streams_data:/app/Videos

volumes:
  streams_data:
