version: '3.3'
services:
   hlstream:
      build: .
      image: hlstream
      restart: unless-stopped
      command: ./full_code/full_pipeline
      ports:
         - '8080:8554'
      volumes:
         - streams_data:/app/Videos

volumes:
   streams_data:
